### ISSUE TITLE
Delete comments

### ISSUE THREAD

**Issue by ChristherLenander** [VirtusLab-Open-Source/strapi-plugin-comments#114]
How can I delete comments in the comments plugin view?

**Comment by cyp3rius** [comment]
@ChristherLenander only author is able to remove comment, moderator is able to block them to not change / break the flow of discussion and sometimes reasoning of ban etc.

Hope it helps.

**Comment by ChristherLenander** [comment]
I want to be able as Super Admin to delete comments. Especial in development mode. When It's just for testing and development.

**Comment by cyp3rius** [comment]
At this very moment we're not considering adding such functionality even for super admin. 

In testing / development mode you might use the [Delete Comment](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments#delete-comment) endpoint exposed for Client.
