### ISSUE TITLE
bad word check is not working good

### ISSUE THREAD

**Issue by ChristherLenander** [VirtusLab-Open-Source/strapi-plugin-comments#116]
We use swedish language in the comment and nice words get flaged as bad words.
I guess the bad word checker doesn't care about other languages than english.

How could we disable the check for bad words?

This text in swedish the the bad word check strikes down on. The "bad" word in the text is "slag". In this context it's mean shot.

Swedish:
"Jag spelade hålet så under U.S. Amateur här 2017 och det var min lagkamrat vid Oklahoma State, Zach Bouchou, som kom med idén. Den linjen passar mitt öga bättre och slår jag den rätt så har jag ett bra slag in, förklarade Hovland efter sin fina 64-rond på fredagen."

Google translate (English)
"I played the hole like that during the U.S. Amateur here in 2017 and it was my Oklahoma State teammate, Zach Bouchou, who came up with the idea. That line suits my eye better and if I hit it right, I have a good shot in, Hovland explained after his nice 64-lap on Friday."

**Comment by cyp3rius** [comment]
@ChristherLenander You can disable it using Settings page. 

In next releases we plan to introduce possibility to customize bad words list.

**Comment by ChristherLenander** [comment]
Ok. But what about the current situation? How can we disable the bad word check?

This is something that should not be implemented by default. It should be up to the developer to add such feature in the their project.

**Comment by cyp3rius** [comment]
As I wrote, you can disable bad words filtering using Settings Page. Go to Settings -> Comments Plugin -> Configuration

**Comment by ChristherLenander** [comment]
![bad word](https://user-images.githubusercontent.com/49711748/155026543-04c6167b-da85-448e-82ed-13376f16a0a9.jpg)

It is disabled what I can see.

**Comment by cyp3rius** [comment]
Yep, seems something is wrong.
Will pick it up early morning and release fixed version.

**Comment by ChristherLenander** [comment]
Thanks 👍

**Comment by cyp3rius** [comment]
@ChristherLenander  released as part of `v2.0.8`. There was a misleading property state on the Settings UI. Now turn on / off works as expected.

**Comment by ChristherLenander** [comment]
Thanks 👍

**Comment by ChristherLenander** [comment]
Tested it and it worked now. Thank you again. Nice plugin 👍
