### ISSUE TITLE
Strapi marketplace documentation and github documentation is not in sync

### ISSUE THREAD

**Issue by Uluwatta** [VirtusLab-Open-Source/strapi-plugin-comments#118]
![image](https://user-images.githubusercontent.com/15074285/156136671-05ab9b2c-7c47-4dc2-8a4d-3f2eb374a284.png)
(/api should be appended on the example URL)

Assume this is a static content build delay on strapi marketplace side given that @cyp3rius committed these doc changes Yesterday ?

**Comment by cyp3rius** [comment]
Yep, aware of it. It will be updated on Marketplace with next release (Strapi Marketplace takes it from npm)

**Comment by Uluwatta** [comment]
@cyp3rius acknowledged and thanks.

I'll closed this issue as this has been taken into the account.
