### ISSUE TITLE
Error 403 Forbidden in Strapi v4.1.5

### ISSUE THREAD

**Issue by cakfan** [VirtusLab-Open-Source/strapi-plugin-comments#124]
I try to post a new comment, I get this error :

![Screenshot (27)](https://user-images.githubusercontent.com/20588976/160322015-e08cc6fa-7ab4-4358-84ee-b565338991fc.png)

![Screenshot (29)](https://user-images.githubusercontent.com/20588976/160322154-691012af-ad49-4580-bc2a-6d4993ae8b30.png)

How to fix this error?

**Comment by cyp3rius** [comment]
Hello @cakfan , as for every Strapi Collection if you would like to use it outside you must configure it via `Settings -> Users & Permissions plugin -> Roles`:
- `Public` - if you want to open it for all
- `Authenticated` - if you want to open it only for Strapi registered users

Than go to `Comments` and enable methods you're interested in.

**Comment by cyp3rius** [comment]
Closing, in case of need re-open please.

**Comment by cakfan** [comment]
> Hello @cakfan , as for every Strapi Collection if you would like to use it outside you must configure it via `Settings -> Users & Permissions plugin -> Roles`:
> 
> * `Public` - if you want to open it for all
> * `Authenticated` - if you want to open it only for Strapi registered users
> 
> Than go to `Comments` and enable methods you're interested in.

I appreciate your help! 👏

**Comment by KaKi87** [comment]
Hi,
I would like to suggest adding this to the README.
Thanks
