### ISSUE TITLE
After setup comments are missing on model

### ISSUE THREAD

**Issue by kwiat1990** [VirtusLab-Open-Source/strapi-plugin-comments#127]
Hey, I'm running the newest version of Strapi (`v4.1.7`) and I have installed the comment plugin and done the initial setup from the Strapi dashboard - everything accordingly to the docs.

After all those steps I don't see any relation between comments and my models as well as comments field doesn't come up when I fetch models. I had also enabled comment plugin in the `plugins.js` to see if that will make any difference but it didn't. Could somebody please point out what I'm missing?

Or everything I will ever see is under that endpoint `api/comments/:relation` and comments won't be a part of the model's response, e.g. `api/articles` won't contain `comments` field?

**Comment by cyp3rius** [comment]
Thats exactly as you described @kwiat1990, you must use the API to fetch comments. For ease of use and flexibility we have dropped the poly relations in `v2.x`.

All what you must do is to setup the plugin using the Settings page.

**Comment by cyp3rius** [comment]
Closing as I see your reaction for my response @kwiat1990 :)
