### ISSUE TITLE
Comments are broken if user was deleted

### ISSUE THREAD

**Issue by kwiat1990** [VirtusLab-Open-Source/strapi-plugin-comments#137]
Hi, I’ve noticed that when a user, which posted a comment, get deleted, then comments view in Strapi dashboard is broken due to an error (reading property name of undefined). It happens because `author` field is relational and in case a user get deleted, all comments of this user won’t contain that field anymore. 

I think it’s a bit of a problem if an app let users delete their accounts.

**Comment by cyp3rius** [comment]
Fix released as part of `2.1.5`
