### ISSUE TITLE
[CU-2eap4ev] Add option to inform commenter via mail about reply

### ISSUE THREAD

**Issue by kwiat1990** [VirtusLab-Open-Source/strapi-plugin-comments#139]
I would like to propose a new feature, which would give commenters an option to get informed in the case someone responded to their comments. It's something most social sites does have as well as blog platforms.

**Comment by cyp3rius** [comment]
Noted @kwiat1990 , adding to the backlog :)

**Comment by cyp3rius** [comment]
Released as part of `v2.1.6`.
