### ISSUE TITLE
Dashboard UI problems

### ISSUE THREAD

**Issue by kwiat1990** [VirtusLab-Open-Source/strapi-plugin-comments#145]
Hey, I have tried the new release and I've noticed some problems, which bothers me a little bit:
1. I can filter comments only by `message`. Other fields like `threadOf` or `entry` are not available: <img width="500" alt="image" src="https://user-images.githubusercontent.com/19494075/169823901-13d9299f-52df-4ce3-8363-e4bfc0a4ce19.png">
2. The search seems to be broken as I get `No comments match the search` all the time. 
3. In the abuse report view, checkboxes are not clickable: <img width="500" alt="image" src="https://user-images.githubusercontent.com/19494075/169824787-4b1f6703-899b-441e-9764-417a62324220.png">

**Comment by cyp3rius** [comment]
@kwiat1990 point no 3 fixed in release `v2.1.7`

**Comment by cyp3rius** [comment]
Closing now because rest of points are related to upcoming advanced filtering feature.
