### ISSUE TITLE
Dashboard Error 500: comments.app.components.notification.error

### ISSUE THREAD

**Issue by matepaiva** [VirtusLab-Open-Source/strapi-plugin-comments#146]
# Debug process

1. When I visit /admin/plugins/comments/discover to see the comments, a lot of errors happens with the same message as the image below.
2. I have published and pending comments and I can GET them via API, so that part is working as expected.
3. The plugin is making a GET request to /comments/moderate/all and that request is returning status 500. I think the problem is there.
4. Therefore, I verified the log and found the following error: `select `t0`.* from `articles` as `t0` where (`t0`.`id` in (124260, NaN)) - ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause' Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'`
5. Here you can see the API GET response that is working fine: https://data.anteprojectos.com.pt/api/comments/api::article.article:124260/flat/

> **Note:** The problem only happens at the backoffice and does not affect the API.

I hope the info above helps you with the debug process :)

![image](https://user-images.githubusercontent.com/9984086/170289674-2440e5fb-9a3a-4c95-aa84-89a04783096b.png)

**Comment by cyp3rius** [comment]
@matepaiva 

can you please provide the `article` collection you're using and how many of them you've got created? That seems for me like a limit issue as `NaN` appears in the automated DB query.

Also plugin config is going to be welcome.

**Comment by matepaiva** [comment]
Thanks for investigating it with me!
- I am using the latest version of both plugin and Strapi;
- my article collection has 10217 items;
- my config:
```
comments: {
    enabled: true,
    config: {
      badWords: false,
      moderatorRoles: [],
      approvalFlow: ['api::article.article'],
      entryLabel: {
        'api::article.article': [
          'Title',
          'title',
          'Name',
          'name',
          'Subject',
          'subject',
        ],
      },
    },
  },
```

**Comment by khocef** [comment]
i have the exact same error, what i did is add subcomment and then delete the parent thread.

**Comment by cyp3rius** [comment]
> i have the exact same error, what i did is add subcomment and then delete the parent thread.

@khocef you've deleted the thread in database? Or using the `delete` endpoint of client service?

**Comment by khocef** [comment]
@cyp3rius using the delete endpoint 

```javascript
remove(commentId: number, pageId: number, authorId: number): Observable<any> {
    return this.http.delete(`http://localhost:1337/api/comments/api::page.page:${pageId}/comment/${commentId}?authorId=${authorId}`);
}
```

**Comment by cyp3rius** [comment]
Thanks for confirming, will check that also

**Comment by cyp3rius** [comment]
@khocef this issue somehow has been fixed in `v2.1.7`, can you check and confirm?

@matepaiva still working on a big set of entities.

**Comment by khocef** [comment]
@cyp3rius thank you a lot, its working great now <3

**Comment by Dope-Engineers** [comment]
It's happening again in v2.2.1

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/77929890/200997863-88d0c61e-6d23-4667-af68-42d993ed59ad.png">

Here is my settings
<img width="958" alt="image" src="https://user-images.githubusercontent.com/77929890/200997922-c5eb58f3-cfeb-4caf-8d09-59f676e9e4a1.png">


I tried deleting all comments, remove plugin and reinstall, but still no luck at all.

**Comment by cyp3rius** [comment]
@Dope-Engineers case with large set of comments is exactly what we already found but it is a modification in the Strapi core libs. We are working on some custom solution here, directly in a plugin

**Comment by betoflakes** [comment]
Sitll happening . The last update brokes my extensions too. We really are waiting your update.,

**Comment by OliveiraCleidson** [comment]
I had the same issue so I updated to version 2.2.4 and it worked too.

**Comment by cyp3rius** [comment]
Closing as seems to be fixed in recent releases.
