### ISSUE TITLE
avatar not showing in admin section

### ISSUE THREAD

**Issue by Dope-Engineers** [VirtusLab-Open-Source/strapi-plugin-comments#154]
Below is the body I got from GET method, eveything seems to work fine but in the avartar doesn't display in the admin section.

`[
    {
        "id": 53,
        "content": "My comment",
        "blocked": false,
        "blockedThread": false,
        "blockReason": null,
        "removed": null,
        "approvalStatus": null,
        "createdAt": "2022-07-31T03:23:27.604Z",
        "updatedAt": "2022-07-31T03:26:19.882Z",
        "gotThread": false,
        "author": {
            "id": 1,
            "name": "master-admin",
            "email": "master-admin@mail.com",
            "avatar": "https://static4.depositphotos.com/1011415/285/v/450/depositphotos_2855252-stock-illustration-little-jack-russel.jpg"
        },
        "children": []
    }
]`

<img width="600" alt="image" src="https://user-images.githubusercontent.com/77929890/182009003-56aa72c8-a21b-4b73-a34f-e42d9290c619.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/77929890/182009137-aac81a59-90f4-444f-be01-f3c1cc5dd733.png">

I tied inspecting the admin page and it appears to have image url in the image tag already. Here is the avatar image url 'https://static4.depositphotos.com/1011415/285/v/450/depositphotos_2855252-stock-illustration-little-jack-russel.jpg'

<img width="585" alt="image" src="https://user-images.githubusercontent.com/77929890/182009104-9530d266-868c-4f96-ad53-8bf55a9fe76e.png">

**Comment by cyp3rius** [comment]
Hello @Dope-Engineers ,

I've checked all the things around `avatar` in our codebase and indeed all seems to be fine from solution perspective. My guess is that Deposit Photos provider got some `origin` filtering applied to not allow use their photos directly outside of same origin (their own service). Try please with any other random image and it should work, I did the same with expected result.

**Comment by Dope-Engineers** [comment]
@cyp3rius I've tried changing the image url to another link as you suggested `https://www.slazzer.com/static/images/sample/jpg/demo-001.jpg` and it's showing the same problem. 
Not sure if my Strapi version is what causing the issue, what version are you on, mine is `@strapi v4.3.6 `with `strapi-plugin-comments v2.1.8`?
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/77929890/188107713-d73bf13d-90ff-43a8-8042-5260d8c5eb45.png">
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/77929890/188110656-2c81ab32-b193-44f6-88eb-2d992c7612a5.png">

**Comment by cyp3rius** [comment]
You know those are external resources so I assume strapi don't have nothing to do with it especially all are present in the HTML. Can you please check Network Console and see why those images not being loaded? Maybe request is blocked in your network?

**Comment by Dope-Engineers** [comment]
My Apologies, I tried with my image uploaded to my own server and it worked! @cyp3rius I will try to check what is blocking.
