### ISSUE TITLE
Endpoints are not available. 4.3.3

### ISSUE THREAD

**Issue by idesignzone** [VirtusLab-Open-Source/strapi-plugin-comments#155]
After installing strapi Comments plugin endpoints are not available. 

```
    "@strapi/plugin-graphql": "^4.3.3",
    "@strapi/plugin-i18n": "^4.3.3",
    "@strapi/plugin-users-permissions": "4.3.3",
    "@strapi/strapi": "4.3.3",
    "mysql": "2.18.1",
    "strapi-plugin-comments": "^2.1.7",
    "strapi-plugin-import-export-entries": "^1.5.0",
    "strapi-plugin-sitemap": "^2.0.8"
```

Example query

```
query {
  findAllFlat(
    relation: "api::page.page:1"
    filters: { content: { contains: "Test" } }
  ) {
    id
    content
    blocked
    threadOf {
      id
    }
    author {
      id
      name
    }
  }
}
```

Error: "Cannot query field \"findAllFlat\" on type \"Query\"."

Note: all Enspoints are checked in settings/users-permissions/roles

**Comment by cyp3rius** [comment]
Hello @idesignzone , 

can you please check the solution here: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/117#issuecomment-1056750814

I'm going to update the docs with this trick.

**Comment by idesignzone** [comment]
@cyp3rius relation: "api::post.post:1" is also different in Docs.

Docs: relation: "api::page.page:1"
Working: relation: "api::post.post:1"

**Comment by cyp3rius** [comment]
@idesignzone relation you're mentioning is just an example which is valid in terms of Strapi UID generator for Collections :) Of course it depends how you're going to name your collection or single time.
