### ISSUE TITLE
400 BadRequestError | Unable to POST a comment to postID

### ISSUE THREAD

**Issue by csharpee** [VirtusLab-Open-Source/strapi-plugin-comments#166]
* Send POST to: https://example.com/api/comments/api::post.post:16

In graphql, 

### Query
```
mutation createComment {
  createComment(
    input: {
      id: "123"
      relation: "api::post.post:16"
      content: "Hello World!"
    }
  ) {
    id
    content
  }
}
```

### Error
```
{
  "error": {
    "data": null,
    "error": {
      "status": 400,
      "name": "BadRequestError",
      "message": "{\"status\":400,\"name\":\"Strapi:Plugin:Comments\",\"message\":\"No content received\"}"
    }
  }
}
```

Note: For testing, comments is open to public.

**Comment by cyp3rius** [comment]
Hello @csharpee,

I've tested your query and indeed it drops error but a bit different like:
```
"message": "Field \"id\" is not defined by type \"CreateComment\".",
```

Please try same query without `id` provided in `input`. After dropping, works for me.

**Comment by csharpee** [comment]
I tested without the ID and I received a different error on Firefox: `NetworkError when attempting to fetch resource`, then again with Google Chrome: '"error": "Failed to fetch schema. Please check your connection"`

It may be a nginx config issue or possibly graphql configuration. 

This is what I *tested*
```
# Write your query or mutation here
mutation createComment {
  createComment(
    input: {
      relation: "api::post.post:16"
      content: "Hello World!"
    }
  ) {
    id
    content
  }
}
```

**Comment by cyp3rius** [comment]
Strapi got built-in GrapQL playground. Try your query on `localhost:1337/graphql` then we will know if thats gql or nginx issue.

**Comment by cyp3rius** [comment]
Closing because lack of response.
