### ISSUE TITLE
Plugin requires reinstalling to appear on admin panel

### ISSUE THREAD

**Issue by fadinasr** [VirtusLab-Open-Source/strapi-plugin-comments#176]
Hello! 

I'm using `Strapi v4.5.3` and `strapi-plugin-comments v2.2.1` and I can't see the plugin locally (even after building) until I reinstall the plugin and build again.

**Comment by cyp3rius** [comment]
Trying to reproduce. Can you please provide more details of your env @fadinasr ?

**Comment by cyp3rius** [comment]
Closing as no active.
