### ISSUE TITLE
Incorrect graphql field

### ISSUE THREAD

**Issue by Malarkey-Jhu** [VirtusLab-Open-Source/strapi-plugin-comments#182]
I follow the readme and download the latest version of plugin which is 4.5.5.
However, there is no findAllInHierarchy in graphql query and all other fields slisted in the readme. e.g. createComment. Instead there are fields like commentsComment(id: ID): CommentsCommentEntityResponse 

And also, the plugin creates table like this: comments_comment, comments_comment-report. Which is a little bit wired, not sure if it is correct.

strapi-version: 4.5.4
strapi-plugin-comments: 4.5.5

![截圖 2022-12-30 下午12 23 04](https://user-images.githubusercontent.com/36290564/210034327-08ded961-37bf-47c8-831d-5b1e1603a04f.png)

<img width="312" alt="截圖 2022-12-30 下午12 24 04" src="https://user-images.githubusercontent.com/36290564/210034415-d2283f3e-21b6-4b24-a47a-d25d0c4b18ec.png">

**Comment by Malarkey-Jhu** [comment]
Also, how can I uninstall this plugin fully. Right now, I run yarn remove strapi-plugin-comments and manully delete the tables in db. Yet, I realize there are some places that need to be cleaned as well such as strapi_database_schema

**Comment by Malarkey-Jhu** [comment]
in plugin.js file

```js
module.exports = ({ env }) => ({
  comments: {
    enabled: true,
    config: {
      moderatorRoles: [],
      badWords: true,
      enabledCollections: [ 'api::article.article' ],
      approvalFlow: [],
      entryLabel: {
        'api::article.article': [ 'Title' ]
      },
      reportReasons: {
        BAD_LANGUAGE: 'BAD_LANGUAGE',
        DISCRIMINATION: 'DISCRIMINATION',
        OTHER: 'OTHER'
      }
    }
  },
  graphql: {
    enabled: true,
  }
});
```

**Comment by cyp3rius** [comment]
Hello @Malarkey-Jhu ,

That seems plugin GQL hasn't been initialised properly for you. Please check if you've got such entry in the GQL schema:

```createComment(input: CreateComment!): CommentSingle!```

If yes, than all is fine. If not, please provide more detailed info about env and your Strapi config.

In terms of DB tables, that's something created automatically by Strapi itself based on entities definitions. Not something we control, as well as during the `uninstall` process.

**Comment by cyp3rius** [comment]
Closing as outdated.

**Comment by thekeels** [comment]
I'm having the same issue, strapi 4.9, strapi-plugin-comments 2.2.9

**Comment by cyp3rius** [comment]
@thekeels I assume you've provided  comments plugin before graphql intte `plugins.js`?

**Comment by thekeels** [comment]
@cyp3rius No, the way I read the documentation it sounded like for 2.0.3 and newer you can just use the GUI to configure the settings, without doing anything to the plugins.js file.

**Comment by cyp3rius** [comment]
Check this from readme as well: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments#additional-gql-configuration

**Comment by thekeels** [comment]
Thanks, that was the problem. I didn't have graphql or comments defined in my plugins.js file.
