### ISSUE TITLE
Request. create some examples in React or Postman

### ISSUE THREAD

**Issue by elmcapp** [VirtusLab-Open-Source/strapi-plugin-comments#197]
It's a little hard to understand the documentation. It would be beneficial to create a YouTube video or include an Examples folder on how to use this system. React Project and Postman. This way we can have a better understanding how to query using rest api because the docs currently a little confusing.

**Comment by themtaysw** [comment]
i dont really agree, docs are really good written and if you struggle with docs i think you should spend some more time understanding at least a bit about coding. but im not here to disrespect you i want to help so what is your issue? what are you struggling with?

**Comment by cyp3rius** [comment]
Closing. There are already examples [here](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments#-examples)
