### ISSUE TITLE
When I install in strapi 4.5.5, I could open /admin uri

### ISSUE THREAD

**Issue by Koourl** [VirtusLab-Open-Source/strapi-plugin-comments#206]
When I install in strapi 4.5.5, I could open /admin uri. There is nothing response but the termial tell me the response is 200

**Comment by alejo4ragon** [comment]
Me pasa lo mismo con strapi 4.9.2 deja de aparecer el dashboard

**Comment by cyp3rius** [comment]
@Koourl may I ask for more details?
- `package.json`
- version of `node`
- snapshot of `plugins.js`

@alejo4ragon english please.

**Comment by IrethHernandez** [comment]
same here with:
strapi v4.9.0
node v19.8.1
package.json:

![image](https://user-images.githubusercontent.com/42724705/236120218-b972211d-c080-4607-a040-6901080e67a9.png)

plugins.js: 

![image](https://user-images.githubusercontent.com/42724705/236120154-7134c1cb-de59-457e-b1c3-5ddd51040e43.png)

**Comment by cyp3rius** [comment]
@IrethHernandez if I get you right, when you add the newest version of plugin to presented `package.json` it does not start? 

1. Does that throw any issues in the console? 
2. Have you run `build` before running?

**Comment by bennydv** [comment]
Same here. I'm on `node v14.20.0`

I can built and run Strapi without errors. The admin is blank and gives me this error in the console:

![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/assets/37837312/64f55292-9b00-46bc-9407-72dcd1cb3b10)

Config:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/assets/37837312/38781dbb-7dd1-4046-b97c-06978c4cfd0a)

Package
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/assets/37837312/8c8352f4-d1e0-442b-89c1-e337f4ffaeb0)


Any help is appreciated 😉

**Comment by cyp3rius** [comment]
Seems the issue might be caused by lack of default in the file `admin/src/index.js`

May I ask any of you to do a small modification of the line:

`registerTrads({ locales })` -> `registerTrads({ locales = [] })`

I cannot reproduce this issue, that's why the ask. Do this in the `node_modules/strapi-plugin-comments` and rebuild project.

**Comment by bennydv** [comment]
Ok, the problem was actually really simple 😬

I had as locales `['en', 'nl']`. The `nl` property was missing from the `trad Object` in the file `/translations/index.js`.
After adding the nl.json and the property, it all works fine.

Thanks for the help @cyp3rius !

**Comment by cyp3rius** [comment]
Yep that might happen if you've got custom locales :)
