### ISSUE TITLE
How do you add new fields to comments?

### ISSUE THREAD

**Issue by SM2DevLLC** [VirtusLab-Open-Source/strapi-plugin-comments#211]
I'm trying to add some additional fields to comments, but I don't see a way to add fields via the admin and nothing is mentioned in the docs for this? Specifically I am trying to add a relation for "likes", but I don't see a way to handle this.

**Note:** I did see this, but the language here makes no sense, and the link goes to a dead page.

"For developers who upgrades their Strapi instance custom field from Comments plugin is available. Custom field can be picked from content types' edit page or added in definition file.

Read more about this feature in [Strapi's docs](https://docs-next.strapi.io/user-docs/latest/plugins/introduction-to-plugins.html#custom-fields)."

**Comment by SM2DevLLC** [comment]
Sorry for all the questions btw.

**Comment by SM2DevLLC** [comment]
@cyp3rius Thanks! I'll take a look at that.

**Comment by janlew** [comment]
Hello, I try to add custom field "rate" to comments.
I copied `comment.js` code from `node_modules/strapi-plugin-comments` and added it to `src/extensions/strapi-plugin-comments/content-types/comment.js`, then added code for "rate" to "attributes".
`rate: {
      type: "text",
      configurable: false,
      required: true,
    },`

But it's not working, when I try to add "rate" with graphql I got message: "Field \"rate\" is not defined by type \"CommentsCommentInput\"."
Please help, I follow [this](https://docs.strapi.io/dev-docs/plugins-extension#extending-a-plugins-content-types) to extend content-types :<

**Comment by Eyon42** [comment]
I'm having the same problem. I can add custom fields, but they aren't added to the graphQL schema
