### ISSUE TITLE
Relation for field related does not exist. Check your payload please.

### ISSUE THREAD

**Issue by giorgosn** [VirtusLab-Open-Source/strapi-plugin-comments#215]
I am doing this post request:
{
  "author": {
    "id": "1",
    "name": "Joe Doe",
    "email": "jdoe@sample.com"
  },
  "content": "My sample response"
}

and I am getting this error as a responce:
{
    "data": null,
    "error": {
        "status": 400,
        "name": "BadRequestError",
        "message": "{\"status\":400,\"name\":\"Strapi:Plugin:Comments\",\"message\":\"Relation for field \\\"related\\\" does not exist. Check your payload please.\"}"
    }
}

Can someone help me on what I am doin wrong?

**Comment by JeremyMCastillo** [comment]
Based on where the error message comes from, it seems like the issue may be with the endpoint you are using. From the documentation, endpoints should be formatted like this:

`POST <host>/api/comments/api::<collection name>.<content type name>:<entity id>`

This error is triggered when the `<content type name>` is not associated with the `<collection name>`. Make sure you're trying to post a comment to a valid Collection Type, and that your URL is formatted correctly.

**Comment by cyp3rius** [comment]
Closing because no feedback from reporter.
