### ISSUE TITLE
Where the hell is pagination?

### ISSUE THREAD

**Issue by Cogitoergo** [VirtusLab-Open-Source/strapi-plugin-comments#217]
Are you kidding me there's no pagination for hierarchical structure? Useless plugin just wasted a week of my time.

**Comment by cyp3rius** [comment]
Before releasing emotions I would advice to read the readme ;)

**Comment by glacierck** [comment]
@cyp3rius Although he is terrible, the fact is that this query function is very meaningless。

**Comment by cyp3rius** [comment]
@mkmak2 please analyze the way to provide the pagination as well to hierarchical query.

Note: That should paginate root level comments only and get all the nested structures of each of them.

@glacierck May I ask you to create separated issue which we are going to mark as a backlog item?
