### ISSUE TITLE
'Author Removed' on Admin Dashboard if 'user-permissions' collection has no 'avatar' field

### ISSUE THREAD

**Issue by garrettfritz** [VirtusLab-Open-Source/strapi-plugin-comments#220]
It seems that the 'author' field is not populating at all if there is no 'avatar' property on the strapi user object.  We are using a different named field ('image') for an application that we recently added comments to and we'd rather not fully refactor it to change this name.  Rather, can we just get the author to populate even if there is no 'avatar'?  

Adding a 'media' object named 'avatar' on the user makes the dashboard work great even though we dont actually use the field, would be nice if we didnt need this work around or even better if it would allow configuration of what the name of our specific 'avatar' field is.
![Screenshot 2023-07-11 at 9 29 52 AM](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/assets/11617610/775df2fc-1ea4-488e-a0e1-de04521da4e1)

**Comment by vitalii-khymchuk** [comment]
+1
same issue

**Comment by bndrgroup** [comment]
+1 same here

**Comment by cyp3rius** [comment]
Investigating

**Comment by cyp3rius** [comment]
Fixed in `v2.2.12`
