### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'toString')" 

### ISSUE THREAD

**Issue by TheWirsing** [VirtusLab-Open-Source/strapi-plugin-comments#221]
I am using Strapi 4.11.3 and the current plugin version in an docker enviroment. I keep getting the error after adding a comment field to a collection type, single type or component when I try to edit a corresponding item in the content manager.

![strapibug](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/assets/47576650/947e7709-8814-4084-a22e-4a7ae7615e62)

**Comment by Dell-it** [comment]
I get the same thing on a clean build 4.11.7 when adding a custom field on the content type editing page. The entity editing page at this moment looks like this:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/assets/69255597/4105804c-b780-4962-89c2-1413ec947162)

**Comment by FightM9** [comment]
Same thing!
Error when creating a new entity with a custom field

> Woops! Something went wrong. Please, try again.

![err](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/assets/57234116/2851e490-340a-4829-8f85-0b34a3149999)

STRAPI VERSION: `v4.11.7`
NODE VERSION: `v18.12.0`
Strapi Plugin Comments: `v2.2.11`

**Comment by cyp3rius** [comment]
Fixed in `v2.2.12`
