### ISSUE TITLE
[CU-86934hnmg] How to remove ’related‘ from the returned result

### ISSUE THREAD

**Issue by glacierck** [VirtusLab-Open-Source/strapi-plugin-comments#239]
/api/comments/api::article.article:1209/flat

I am searching for comment results under the article by Ids, but each result has a 'related' attribute. Is it necessary to constantly replay the article object?

**Comment by cyp3rius** [comment]
We will check the way to make it optional.

**Comment by CodeVoyager** [comment]
Hi @glacierck 

There's a PR addressing your query. Have a look, please.
