### ISSUE TITLE
Getting error on Report Abuse API 

### ISSUE THREAD

**Issue by hassan-debug** [VirtusLab-Open-Source/strapi-plugin-comments#246]
When i call report-abuse api i get below error 

> OPENSSL_internal:WRONG_VERSION_NUMBER

here is sample endpoint

> https://localhost:1337/api/comments/api::article.article:164/comment/10/report-abuse

Strapi version 4.15
node : 18.13

**Comment by cyp3rius** [comment]
Hello @hassan-debug,

Thing you're referring to is a Strapi configuration for SSL and how from you client you're calling Strapi endpoints. There is nothing related to the Comments Plugin itself. 

Please follow Strapi docs to sort that out.
