### ISSUE TITLE
Permissions is not iterable

### ISSUE THREAD

**Issue by sadeq-qafari** [VirtusLab-Open-Source/strapi-plugin-comments#247]
When trying to open 
Strapi Settings -> Section: Comments Plugin -> Configuration
Im facing this error:
`permissions is not iterable`

Im new to strapi and im using latest version

**Comment by MarinosTBH** [comment]
@sadeq-qafari  
I faced the same problem on strapi 4.19.0 and it looks like that this plugin is not up to date with the strapi releases.
Use an older version of strapi it may work

**Comment by cyp3rius** [comment]
Checking with newest versions. Fix should be in next 2-3 days.

**Comment by cyp3rius** [comment]
Fix goes live with version `2.2.16`
