### ISSUE TITLE
When can we expect Strapi 5 support?

### ISSUE THREAD

**Issue by anshul-fitsib** [VirtusLab-Open-Source/strapi-plugin-comments#271]
Can you confirm the target date for the plugin update to support Strapi 5?

**Comment by cyp3rius** [comment]
We are targeting mid October 2024

**Comment by ghmasood** [comment]
October has ended today....

**Comment by cyp3rius** [comment]
We are still working on porting, it's not that easy with such complex functionality ;) next weeks should give us first beta

**Comment by ghmasood** [comment]
thanks

**Comment by pocahontas123** [comment]
Thanks

**Comment by cyp3rius** [comment]
It has been just released in version `3.0.0-beta.0`. Keep in mind it's early beta and the migration was HUGE so might be still a bit buggy - but we're working on it daily to fix and improve the quality :)
