### ISSUE TITLE
Autopopulate on different authorType ?

### ISSUE THREAD

**Issue by tiberiumihai** [VirtusLab-Open-Source/strapi-plugin-comments#39]
I've see that the authorUser can be used for strapi user and other author particular fields can be used for other type of users (let's say a profile). I don't like this method because if the user changes his name or his avatar, these fields become obsolete.

And because I store the user account data (auth) in a different content type than the user profile data, is it possible to create a comment using in payload: 
```{ authorType: "profile", authorId: "<profile-id>" }```
and the plugin to auto-populate this attribute?

Maybe this way, the duplicated fields can become only one, strapi user or other related content type (user profile).

I would look up on how I might add this functionality but I'm not entirely sure if this is what the plugin wants in the future.

Let me know and I can take a look.

Thanks for the awesome work!

**Comment by cyp3rius** [comment]
Hello @tiberiumihai,
Your case is not a common one unfortunately :) Anyway populating a user profile sounds like a good idea. In my opinion it should be done much more flexible by using configuration parameters, where you are going to set a reference to Content Type that is dedicated for profile.
Such approach won’t cause breaking change in the codebase and API payloads.

What you think?

**Comment by tiberiumihai** [comment]
You are right. When I extend the User content type from users-permissions by adding profile relation to it, it gets added to the authorUser attribute. Then I only need to specify the "authorUser.profile" in the population array.

I think we can set this up via a config attribute, either as the profile attribute, or either as an option to auto-populate additional fields on authorUser. 

For the testing purposes I just tested using this in findAll service function and it works perfectly:
```
const entities = query && query._q ?
            await strapi.query( model.modelName, pluginName).search(params, ['authorUser', 'authorUser.profile', 'related', 'reports']) :
            await strapi.query( model.modelName, pluginName).find(params, ['authorUser', 'authorUser.profile', 'related', 'reports']);
```

What do you think?

**Comment by cyp3rius** [comment]
We're going to implement it for `v4` supported version.

**Comment by cyp3rius** [comment]
Done as part of #113
