### ISSUE TITLE
Add pre-moderation option

### ISSUE THREAD

**Issue by DennieMello** [VirtusLab-Open-Source/strapi-plugin-comments#45]
Thanks for this plugin! It would be great to add a pre-moderation mode for comments. Add the "moderation" property to each comment, similar to "blocked", and add a button to the admin panel, similar to "Hide comment". And also when changing or creating a comment, set the "moderation" status to true.

**Comment by cyp3rius** [comment]
@DennieMello can you describe in more details expected flow? Sounds interesting :)
