### ISSUE TITLE
Add Endpoint to Unlike Comment

### ISSUE THREAD

**Issue by fated-x** [VirtusLab-Open-Source/strapi-plugin-comments#48]
Thanks for this amazing plugin - it has saved me loads of time! I have been utilizing the endpoint to "like" comments but I would also like to provide my users with the ability to reverse that decision and "unlike" a comment after the fact. Is this on the roadmap? If not, I'm certain many people could benefit from such a feature. Cheers!

**Comment by cyp3rius** [comment]
Thanks @fated-x,

We've had the `Relations` plugin almost ready. Waiting for commercial project decision to expose it. Once published the like option is going to be removed. The `Relations` plugin will allow to define different types of reactions, add / remove them and count per user / type.

Hope that will work :)

**Comment by Nisthar** [comment]
@cyp3rius Thanks for the plugin. 

do you think there is a way to store some additional data (like/dislike) directly in the comments db?
