### ISSUE TITLE
Cannot fetch comments

### ISSUE THREAD

**Issue by kwiat1990** [VirtusLab-Open-Source/strapi-plugin-comments#53]
Hi, after updating the comments plugin (v1.0.1) and the Strapi (v.3.6.2) I noticed that I can't fetch any existing comments using the standard endpoints and the response look like below:
```
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Your filters contain a field 'removed' that doesn't appear on your model definition nor its relations"
}
```
It doesn't matter how I call the endpoint (fetch request, in the browser's URL bar or in Postman) I still get the very same error. At the same time I see that the comment are there (related field on `article`, I tried to fetch comments for, have all of them). Funny enough, fetching all comments with `comments/moderation/all` does work.

I haven't done anything to the code itself, besides mentioned updates, and my config looks like in the documentation.

**Comment by kwiat1990** [comment]
The fast solution was to take a look at the last release and then I saw [this change](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/compare/v1.0.0...v1.0.1#diff-275fb96a4128e259768a2a13341ada4cd01a8af56158decbde2f68d757fcc861). As a quick fix I added the same code to my comment model. After that all endpoints are working again. I assume it should be somehow target in the new release/hotfix or mentioned in the documentation.

**Comment by cyp3rius** [comment]
Good spot @kwiat1990 but that occurs only if you’ve got comment model in extensions, so core one is being overwritten.

We will provide it as a Migration Guide 1.0.0 -> 1.0.1 in documentation.

**Comment by kwiat1990** [comment]
Does it mean that it's not needed anymore to define the model by hand? I can remember it was required in the past or am I wrong?

**Comment by cyp3rius** [comment]
It’s required for content types you want to define comments like: page, post etc. 

Modification of plugin built-in comment model is not required anymore. We have fixed that issue some time ago.

**Comment by kwiat1990** [comment]
Thanks, it's really good to know. If I were aware of this, then I wouldn't encounter the problem in the first place.
