### ISSUE TITLE
[CU-20xz3qe] Moderator can respond to the comment via admin panel

### ISSUE THREAD

**Issue by cyp3rius** [VirtusLab-Open-Source/strapi-plugin-comments#55]
1. Answer should be marked as "moderator" without linking to any existing user. It shouldn't take into account users configuration of plugin.

**Comment by kwiat1990** [comment]
Hi, how should it work exactly?

I think it would come in quite handy if a Strapi user could become one of N roles defined in comment plugin and respond to comments from the dashboard. So, for example I'm a super admin and I would give myself a moderator role in comment plugin. The same I would grant a Strapi user with the author role an author role in comment plugin.

To be honest I want to build such functionality in my frontend, so I can mark the author and the moderator with a label or something similar. This would be just another option for Strapi user to respond to comment.

So generally speaking, there are two functionalities:
1. Possibility to respond to comment direct from the dashboard aka admin panel.
2. Possibility to give a Strapi users one of roles (I would say roles should be defined by plugins users), which would be added to their comment object and then could be easily consumed by the fronted.

**Comment by kwiat1990** [comment]
Hi, ich have tried responding direct from the panel but the `author` object won't get populated completely:
```js
{
  avatar: null,
  email: "lorem@ipsum.com",
  id: "1",
  name: null
}
```

Despite the fact that this user is a super admin and does have first and last name, they both are ignored. What's more, right know there is no indicator that this comment comes from the admin or a staff member.

**Comment by cyp3rius** [comment]
Will investigate this @kwiat1990 and provide fix.
