### ISSUE TITLE
Cannot Open Comments in Dashbaord

### ISSUE THREAD

**Issue by zoharkiks** [VirtusLab-Open-Source/strapi-plugin-comments#59]
Hello, whenever I'm trying to open Comments under the collection types, I'm getting the follwoing error:

![image](https://user-images.githubusercontent.com/61095857/121817197-8d732f00-cc9d-11eb-8581-69f898ee66ed.png)

**Comment by loongmxbt** [comment]
Same error in 3.6.3 (node v14.15.3)

**Comment by FbPalmabit** [comment]
+1

**Comment by cyp3rius** [comment]
This collection is not supported by built-in Content Manager because of usage of advanced polymorphic relations.

We advice to use dedicated interface available in Plugins -> Comments on the left sidebar. This interface is supported by our team.

**Comment by loongmxbt** [comment]
@cyp3rius Hi, the plugin automatically generates "Comments" and "Reports" in Collections. The "Reports" collection is reachable, but the "Comments" collection has errors. So is this Strapi's default behaviour on plugins and how can we "hide" the them from collection types area.

**Comment by cyp3rius** [comment]
That's right, and it has been already introduced as part of #57 but not yet published. We're going to do this in a next version.
