### ISSUE TITLE
Error "TypeError: Cannot read property 'pluginOptions' of undefined"

### ISSUE THREAD

**Issue by leandrolimapt** [VirtusLab-Open-Source/strapi-plugin-comments#62]
Hi, I was installing strapi-plugin-comments on my strapi project and when I enter the comment's collection type, the page doesn't load, and it shows the error "TypeError: Cannot read property 'pluginOptions' of undefined" on the console. 
Could you please tell me if I am doing something wrong?

Thank you!

**Comment by rerecampos** [comment]
Same thing here, I tried to reinstall everything and rebuild the application, but it still has this error.
![image](https://user-images.githubusercontent.com/82174766/125514832-2d9b703d-3e7f-4f96-a234-5306cb6b3b6a.png)

Current strapi version: 3.6.5

**Comment by cyp3rius** [comment]
Hi both, check please #59. That’s expected behavior. You should use dedicated interface in Plugins -> Comments

**Comment by leandrolimapt** [comment]
@cyp3rius
I have the latest version installed and there is no dedicated interface in Plugins -> Comments :(
![Captura de ecrã 2021-07-13 231509](https://user-images.githubusercontent.com/58558734/125532199-885af2ce-eba7-4afb-9837-494356c65180.jpg)

**Comment by rerecampos** [comment]
> @cyp3rius
> I have the latest version installed and there is no dedicated interface in Plugins -> Comments :(
> ![Captura de ecrã 2021-07-13 231509](https://user-images.githubusercontent.com/58558734/125532199-885af2ce-eba7-4afb-9837-494356c65180.jpg)

Here normally appears to me
![image](https://user-images.githubusercontent.com/82174766/125632982-313939d3-ecbf-4e22-a39e-2b519d06cf86.png)

Your app build is probably old, follow these steps to clean up and redo it

- Delete **node_modules, package-lock.json** (or yarn.lock if u use yarn) **& .cache folder**
- npm install / yarn
- npm run build / yarn build
- npm run develop / yarn develop
