### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by G1Joshi** [VirtusLab-Open-Source/strapi-plugin-comments#63]
Deleting a comment is not working in strapi comment plugin,
**I am making a delete request with authorId in json body**

URL- localhost:1337/comments/articles:1/comment:1

Body
```json
{
	"authorId": "1",
	"authorName": "Test",
	"authorEmail": "test@gmail.com"
}
```

Response
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Not provided authorId"
}
```

**On providing authorId on query**

URL- localhost:1337/comments/articles:1/comment:1?authorId=1

Response
```json
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred"
}
```

**Comment by G1Joshi** [comment]
@cyp3rius Can you please look into this issue?

**Comment by cyp3rius** [comment]
Hi @G1Joshi , checking the scenario.

**Comment by cyp3rius** [comment]
Hi @G1Joshi,

I was able to reproduce your issue but it's simply a problem with url you're calling as we don't have proper documentation provided here. What have to be fixed. Try please:

```DELETE localhost:1337/comments/article:1/1?authorId=1```

**Comment by G1Joshi** [comment]
Yeah, @cyp3rius it works for me :)
