### ISSUE TITLE
Delete comment in admin panel?

### ISSUE THREAD

**Issue by alexey13** [VirtusLab-Open-Source/strapi-plugin-comments#66]
Good day! Thank you for your awesome plugin!
As there a way to delete comment in admin panel?
As i understood correctly you hide collection "Comments", right? Because in my admin only "Comments" in "Plugins" section

**Comment by cyp3rius** [comment]
Hi @alexey13 ,

All the actions with comments must be done via dedicated UI that is one of an items in Plugins section. Hope that helps.

**Comment by alexey13** [comment]
Yeah, and we have "Hide" button, but we cant delete, right?

**Comment by cyp3rius** [comment]
In couple of days we will release new version with community contribution in that terms so deleting is going to be possible. For now "hide" is the only option to manage it and mark what we don't want to send to the client UI.

**Comment by alexey13** [comment]
Awesome, thank you!
