### ISSUE TITLE
Comments filtering by relation

### ISSUE THREAD

**Issue by cyp3rius** [VirtusLab-Open-Source/strapi-plugin-comments#7]
Expectation:
 - I would like to see option for filtering by relation like:
   - Relation type (Article, Page, etc.)
   - Entity (My Sample page etc.) - activated after selecting relevant type

**Comment by tiberiumihai** [comment]
I have a slug set for an article. It would be nice if we can get all comments for that given (unique) slug without making 2 requests just to get the article id.

Also, it would be nice if we can paginate comments like using strapi.
```const pagination = `_start=${commentPagination.skip}&_limit=${commentPagination.take}&_sort=created_at:DESC`;```
