### ISSUE TITLE
REQUEST: Expand setup more for newbies.

### ISSUE THREAD

**Issue by MichalNemec** [VirtusLab-Open-Source/strapi-plugin-comments#71]
Hello,
section https://github.com/VirtusLab-Open-Source/strapi-plugin-comments#configuration
is not clear enough. by default Strapi does not have any file custom.js or some sample where to get this from to modify and add values you say in readme.

Can this be expanded?
Thanks

**Comment by cyp3rius** [comment]
Documentation has been updated and reference changed to `plugins.js` to follow Strapi docs.
