### ISSUE TITLE
content-types comments does not appear

### ISSUE THREAD

**Issue by Neyunse** [VirtusLab-Open-Source/strapi-plugin-comments#75]
Hi, I don't know if this is a bug or if I have to create the content-type of comments.
Looking at the screenshots, I can see that the plugin adds a content-type... But in my panel it doesn't appear, I already used "yarn build" and it doesn't solve the problem either.

![imagen](https://user-images.githubusercontent.com/36079551/135947091-88d9e666-8c72-4fb0-8d6f-5bf89e6efd4d.png)

**Comment by cyp3rius** [comment]
@Neyunse  it's not a bug, but a feature ;) The comments is a plugin with own UI (see your left sidebar -> plugins section -> Comments).

All of the collections delivered with Comments are exclusive for it, the only thing you must do is to add proper field in your own collections to link them with comments.
