### ISSUE TITLE
How to add custom fields to comments

### ISSUE THREAD

**Issue by SkipTheDragon** [VirtusLab-Open-Source/strapi-plugin-comments#80]
Hello,
I would like to add an url field to the comment collection, but i don't know where to edit it (can't find it in content-types). Can i add it directly in the sql table?

**Comment by cyp3rius** [comment]
Hello @SkipTheDragon ,

The `Comment` collection is an internal one of the plugin. Anyway if you want to extend it you can simply use the Strapi Extensions mechanism.

1. Go to plugin source: `models` and copy `comment.settings.json`
2. Past the file into your project directory as `extensions/comments/models/comment.settings.json` 

Read more here based on Strapi Content Manager extension: https://strapi.io/documentation/developer-docs/latest/guides/custom-admin.html#update-the-content-manager

Keep in mind that by doing your own extensions, we might be no longer able to support you with issues.

**Comment by Nisthar** [comment]
> 1. Go to plugin source: `models` and copy `comment.settings.json`

Where is this file located?

**Comment by cyp3rius** [comment]
@Nisthar As you see based on the dates, advice was for v3 compatible version :) current v4 supported by plugin in `v2.x` got it managed differently.

You should extend the file from `content-types/comment.js` using Strapi v4 extensions approach.

**Comment by Nisthar** [comment]
@cyp3rius when overwriting the content-type, do i have to create the schema for all the fields that were already there or just the new ones?

**Comment by cyp3rius** [comment]
@Nisthar As that is js file you can import original file and extend proper fields by spread operator. Please follow official Strapi v4 docs for Plugins extensions.

**Comment by Nisthar** [comment]
> @Nisthar As that is js file you can import original one and extend proper fields by spread operator. Please follow official Strapi v4 docs for Plugins extensions.

Are you saying that i can use a .js file instead of the json format?

**Comment by cyp3rius** [comment]
Yes, in v4 its allowed and as you check our codebase we also support it.

**Comment by Nisthar** [comment]
So i can just paste the comment.js file and add the updates in there?

**Comment by Nisthar** [comment]
Ok just tried it, didn't work

pasted comment.js file into ./extensions/strapi-plugin-comments/content-types/comment.js, added some fields and restarted the server. Doesn't seems to work.

**Comment by Nisthar** [comment]
Ok tried adding all into `schema.json` file. it still doesn't return the new fields.

**Comment by Nisthar** [comment]
any update?

**Comment by cyp3rius** [comment]
Let me please back to you on Monday. And also, create separated issue dedicated for v4, do not follow discussion in closed issues.

**Comment by Nisthar** [comment]
> Let me please back to you on Monday. And also, create separated issue dedicated for v4, do not follow discussion in closed issues.

sure, i think there's no need for that now. The solution was to change the plugins name. 👍
