### ISSUE TITLE
GraphQL findAll pagination not working

### ISSUE THREAD

**Issue by Juraso2** [VirtusLab-Open-Source/strapi-plugin-comments#81]
Hello, pagination in findAll query is not working.
I think it is not working because of JSON.parse function want to get a string parameter but query provide an array.
It works when i provide _where_ argument like this
`where: ["{\"_start\":0,\"_limit\":10}"]`

**Comment by cyp3rius** [comment]
Released as part of `1.0.4`. Appreciate your contribution!
