### ISSUE TITLE
Support Strapi v4

### ISSUE THREAD

**Issue by ZDVokoun** [VirtusLab-Open-Source/strapi-plugin-comments#94]
Do you plan to rewrite the plugin to support Strapi v4, which was released a few days ago? There is tutorial from Strapi Blog, if you need it: https://strapi.io/blog/v4-plugin-migration-guide.

**Comment by cyp3rius** [comment]
Hello @ZDVokoun, it's already in progress: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/discussions/92

**Comment by ZDVokoun** [comment]
Oh, thanks for the quick response.

**Comment by sheddy123** [comment]
Hello @cyp3rius How is this plugin implemented. I installed it on the latest strapi version, but calling it via api or attaching it to a relation don't seem to be working

**Comment by cyp3rius** [comment]
@sheddy123 may I ask you to create separated issue for your case? Provide please some broader explanation what the case is.

The plugin is written without db relations to your content types to make it flexible so you don't need to link it anywhere. Just follow [Readme.md](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/tree/feat/strapi-v4#configuration)
